const url = "https://pod.rahpooyan.ir";
// const url = "http://apipod.local";
// const url = "http://podsystem.local";
export default {
    android_package_name: 'com.pod.kiosk',
    store_name: 'direct_download',
    baseURL: url,
    uri :  url,
    socket_url : url,
    support_call:"021 9131 9291",
    support_unit: "211",
    data: {
      configs: {
        translate: 'fa',
        webview: true,
        pay_at_cashier_store: true,
        last_touch_time: 300,
        shwow_alert_touch_time: 30,
        themes:{
          t1:{
            colors:{
              bottom_tab_background : "#194d33",
              bottom_tab_active : "#FFFFFF", 
              bottom_tab_inactive : "#BDBDBD",
              background_gradient : ['#194d33', '#388e3c', '#4caf50'],
              white_1 : "#FFFFFF", 
              white_2 : "#F0F0F0", 
              white_3 : "#EBEBEB", 
              white_4 : "#d1d1d1", 
              white_5 : "#cccccc",
              white_6 : "#BDBDBD",
              ///////////////////////////
              background : '#F6F9FC',
              background2 : '#F1F1F1',
              background3 : '#FFF',
              background4 : '#FFF',
              background5 : '#F9FCFC',
              border : '#d1d1d1',
              border2 : '#dfdfdf',
              text : '#434343',
              text2 : '#333',
              text3 : '#000',
              text4 : '#666',
              text5 : '#999',
              text6 : '#5d5d5d',
              color : '#0088cc',
              error : '#CC0000',
              green : '#309334',
              blue : '#0088cc',
              white : '#FFFFFF',
              black : '#000',
              status : '#dadada',
              shadow : '#000000',
            }
          },
          t2:{
            colors:{
              bottom_tab_background : "#006064",
              bottom_tab_active : "#FFFFFF", 
              bottom_tab_inactive : "#BDBDBD",
              background_gradient : ['#006064', '#0097a7', '#00bcd4'],
              white_1 : "#FFFFFF", 
              white_2 : "#F0F0F0", 
              white_3 : "#EBEBEB", 
              white_4 : "#d1d1d1", 
              white_5 : "#cccccc",
              white_6 : "#BDBDBD",
              ///////////////////////////
              background : '#F6F9FC',
              background2 : '#F1F1F1',
              background3 : '#FFF',
              background4 : '#FFF',
              background5 : '#F9FCFC',
              border : '#d1d1d1',
              border2 : '#dfdfdf',
              text : '#434343',
              text2 : '#333',
              text3 : '#000',
              text4 : '#666',
              text5 : '#999',
              text6 : '#5d5d5d',
              color : '#0088cc',
              error : '#CC0000',
              green : '#309334',
              blue : '#0088cc',
              white : '#FFFFFF',
              black : '#000',
              status : '#dadada',
              shadow : '#000000',
            }
          },
        },
        colors: {
          primary: '#0088cc',
          primary_gradient_start: '#0088cc',
          primary_gradient_end: '#1fb8f4',
          red: '#FF2400',
          green: '#009933',
          blue:'#0088cc',
          red_error: '#CC0000',
          warning: '#FF8800',
          info: '#0099CC',
          white: '#FFFFFF',
          rgba0: 'rgba(0,136,204,0.9)',
          rgba1: 'rgba(0,136,204,0.7)',
          rgba2: 'rgba(0,136,204,0.3)',
          rgba3: 'rgba(0,136,204,0.1)',
        },
        alert: {
          icon_type: 'lottie',
          success: {
            gradient_start: '#007E33',
            gradient_end: '#00C851',
            icon: 'check',
          },
          alert: {
            gradient_start: '#CC0000',
            gradient_end: '#ff4444',
            icon: 'times',
          },
          info: {
            gradient_start: '#0099CC',
            gradient_end: '#33b5e5',
            icon: 'info',
          },
          warn: {
            gradient_start: '#FF8800',
            gradient_end: '#ffbb33',
            icon: 'exclamation',
          },
          question: {
            gradient_start: '#FF8800',
            gradient_end: '#ffbb33',
            icon: 'question',
          },
        },
      },
    },
  };
  